### ISSUE TITLE
NULL namespace prefixes used in AppSchema WFS GetFeature responses

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/inspire-issues#6]
The GML response of a WFS GetFeature request hitting more than one App-Schema complex feature type:

<?xml version="1.0" encoding="UTF-8"?>
<GetFeature version="2.0.0" (...)>
    <Query typeNames="wk_ms_0_gml32:Measurement_gml32">
         <Filter xmlns="http://www.opengis.net/fes/2.0">
              <PropertyIsEqualTo>
                <ValueReference>Measurement_gml32/@gml:id</ValueReference>
                <Literal>ms.1</Literal>
              </PropertyIsEqualTo>
          </Filter>
    </Query>
    <Query typeNames="wk_st_0_gml32:Station_gml32">
         <Filter xmlns="http://www.opengis.net/fes/2.0" xmlns:ps="http://inspire.ec.europa.eu/schemas/ps/4.0" xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3">
              <PropertyIsEqualTo>
                <ValueReference>Station_gml32/@gml:id</ValueReference>
                <Literal>st.1</Literal>
              </PropertyIsEqualTo>
          </Filter>
    </Query>

... Will use a NULL namespace prefix in all returned features:

<?xml version="1.0" encoding="UTF-8" ?>
<wfs:FeatureCollection xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" numberMatched="unknown" numberReturned="4" timeStamp="2018-05-07T09:55:30.106Z" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://localhost:8080/geoserver/schemas/wfs/2.0/wfs.xsd http://www.stations_gml32.org/1.0 file:/Users/ior/gs_null_prefix_test/geoserver-2.13.0/data_dir/data/USE_CASE_0_STATIONS_GML32/stations_gml32.xsd http://www.opengis.net/gml/3.2 http://localhost:8080/geoserver/schemas/gml/3.2.1/gml.xsd http://www.measurements_gml32.org/1.0 file:/Users/ior/gs_null_prefix_test/geoserver-2.13.0/data_dir/data/USE_CASE_0_MEASUREMENTS_GML32/measurements_gml32.xsd")>
    <wfs:member>
        <wfs:FeatureCollection numberMatched="0" numberReturned="0" timeStamp="2018-05-07T09:55:30.106Z">
            <wfs:member>
                <null:Measurement_gml32 xmlns:null="http://www.measurements_gml32.org/1.0" gml:id="ms.1">
                    <null:name>temperature</null:name>
                </null:Measurement_gml32>
            </wfs:member>
        </wfs:FeatureCollection>
    </wfs:member>
    <wfs:member>
        <wfs:FeatureCollection numberMatched="0" numberReturned="0" timeStamp="2018-05-07T09:55:30.106Z">
            <wfs:member>
                <null:Station_gml32 xmlns:null="http://www.stations_gml32.org/1.0" gml:id="st.1">
                    <null:name>station1</null:name>
                    <null:location>
                        <gml:Point srsDimension="2" srsName="urn:ogc:def:crs:EPSG::4326">
                            <gml:pos>1 -1</gml:pos>
                        </gml:Point>
                    </null:location>
                    <null:measurements href="#ms.1"/>
                    <null:measurements>
                        <null:Measurement_gml32 xmlns:null="http://www.measurements_gml32.org/1.0" gml:id="ms.2">
                            <null:name>wind</null:name>
                        </null:Measurement_gml32>
                    </null:measurements>
                </null:Station_gml32>
            </wfs:member>
        </wfs:FeatureCollection>
    </wfs:member>
</wfs:FeatureCollection>

**Comment by nmco** [comment]
Associated pull requests:
* https://github.com/geoserver/geoserver/pull/3073
* https://github.com/geoserver/geoserver/pull/3072

**Comment by fernandor777** [comment]
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOS-8799
